/*
 * Copyright by the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Module Info for Wallet Template
 * Note: relies upon several filename-based Automatic Modules and the
 * BadAss JLink Gradle Plugin for correct operation
 *
 * if you are using IntelliJ and it isn't finding the org.bitcoinj.core, see:
 * https://blog.jetbrains.com/idea/2017/03/support-for-java-9-modules-in-intellij-idea-2017-1/
 * I made it work by adding a filename-based JAR dependency on the output JAR of the 'core' module.
 */
module org.bitcoinj.walletfx {
    requires java.logging;
    requires java.desktop;

    requires javafx.graphics;
    requires javafx.controls;
    requires javafx.fxml;

    requires org.consensusj.supernautfx;
    requires javax.inject;
    /*
     * Although the classes in a SupernautFX app (like this one, hopefully) use annotations
     * from javax.inject and do not import any Micronaut classes,
     * the Bean Definition classes generated by the Micronaut annotation process
     * run inside this module and do require Micronaut classes.
     */
    requires io.micronaut.inject;
    //requires jsr305;  // This is only needed for IntelliJ because IntelliJ doesn't know about the patch-module command apparently
    requires org.slf4j;
    requires org.slf4j.jul;

    requires org.bitcoinj.core;     // Automatic module

    requires org.bouncycastle.provider;
    requires com.google.common;

    requires protobuf.java;
    requires com.google.zxing;
    requires fontawesomefx;         // Filename-based automatic module name

    /* Export/Open Wallet Framework packages */
    exports org.bitcoinj.walletfx;
    exports org.bitcoinj.walletfx.controls;
    exports org.bitcoinj.walletfx.utils;
    exports org.bitcoinj.walletfx.utils.easing;

    opens org.bitcoinj.walletfx to javafx.fxml;
    opens org.bitcoinj.walletfx.controls to javafx.fxml;
    opens org.bitcoinj.walletfx.utils to javafx.fxml;

    /* Export/Open the WalletTemplate App itself -- will eventually be its own module */
    exports wallettemplate;
    
    opens wallettemplate to javafx.fxml, java.base;

}
