// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storedclientpaymentchannel.proto

package org.bitcoinj.protocols.channels;

public final class ClientState {
  private ClientState() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StoredClientPaymentChannelsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .paymentchannels.StoredClientPaymentChannel channels = 1;
    /**
     * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
     */
    java.util.List<org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel> 
        getChannelsList();
    /**
     * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
     */
    org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel getChannels(int index);
    /**
     * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
     */
    int getChannelsCount();
    /**
     * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
     */
    java.util.List<? extends org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannelOrBuilder> 
        getChannelsOrBuilderList();
    /**
     * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
     */
    org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannelOrBuilder getChannelsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code paymentchannels.StoredClientPaymentChannels}
   *
   * <pre>
   * A set of StoredPaymentChannel's
   * </pre>
   */
  public static final class StoredClientPaymentChannels extends
      com.google.protobuf.GeneratedMessage
      implements StoredClientPaymentChannelsOrBuilder {
    // Use StoredClientPaymentChannels.newBuilder() to construct.
    private StoredClientPaymentChannels(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StoredClientPaymentChannels(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StoredClientPaymentChannels defaultInstance;
    public static StoredClientPaymentChannels getDefaultInstance() {
      return defaultInstance;
    }

    public StoredClientPaymentChannels getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StoredClientPaymentChannels(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                channels_ = new java.util.ArrayList<org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel>();
                mutable_bitField0_ |= 0x00000001;
              }
              channels_.add(input.readMessage(org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          channels_ = java.util.Collections.unmodifiableList(channels_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bitcoinj.protocols.channels.ClientState.internal_static_paymentchannels_StoredClientPaymentChannels_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bitcoinj.protocols.channels.ClientState.internal_static_paymentchannels_StoredClientPaymentChannels_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels.class, org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels.Builder.class);
    }

    public static com.google.protobuf.Parser<StoredClientPaymentChannels> PARSER =
        new com.google.protobuf.AbstractParser<StoredClientPaymentChannels>() {
      public StoredClientPaymentChannels parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StoredClientPaymentChannels(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StoredClientPaymentChannels> getParserForType() {
      return PARSER;
    }

    // repeated .paymentchannels.StoredClientPaymentChannel channels = 1;
    public static final int CHANNELS_FIELD_NUMBER = 1;
    private java.util.List<org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel> channels_;
    /**
     * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
     */
    public java.util.List<org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel> getChannelsList() {
      return channels_;
    }
    /**
     * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
     */
    public java.util.List<? extends org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannelOrBuilder> 
        getChannelsOrBuilderList() {
      return channels_;
    }
    /**
     * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
     */
    public int getChannelsCount() {
      return channels_.size();
    }
    /**
     * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
     */
    public org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel getChannels(int index) {
      return channels_.get(index);
    }
    /**
     * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
     */
    public org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannelOrBuilder getChannelsOrBuilder(
        int index) {
      return channels_.get(index);
    }

    private void initFields() {
      channels_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getChannelsCount(); i++) {
        if (!getChannels(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < channels_.size(); i++) {
        output.writeMessage(1, channels_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < channels_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, channels_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code paymentchannels.StoredClientPaymentChannels}
     *
     * <pre>
     * A set of StoredPaymentChannel's
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannelsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.bitcoinj.protocols.channels.ClientState.internal_static_paymentchannels_StoredClientPaymentChannels_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.bitcoinj.protocols.channels.ClientState.internal_static_paymentchannels_StoredClientPaymentChannels_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels.class, org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels.Builder.class);
      }

      // Construct using org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getChannelsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (channelsBuilder_ == null) {
          channels_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          channelsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.bitcoinj.protocols.channels.ClientState.internal_static_paymentchannels_StoredClientPaymentChannels_descriptor;
      }

      public org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels getDefaultInstanceForType() {
        return org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels.getDefaultInstance();
      }

      public org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels build() {
        org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels buildPartial() {
        org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels result = new org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels(this);
        int from_bitField0_ = bitField0_;
        if (channelsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            channels_ = java.util.Collections.unmodifiableList(channels_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.channels_ = channels_;
        } else {
          result.channels_ = channelsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels) {
          return mergeFrom((org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels other) {
        if (other == org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels.getDefaultInstance()) return this;
        if (channelsBuilder_ == null) {
          if (!other.channels_.isEmpty()) {
            if (channels_.isEmpty()) {
              channels_ = other.channels_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureChannelsIsMutable();
              channels_.addAll(other.channels_);
            }
            onChanged();
          }
        } else {
          if (!other.channels_.isEmpty()) {
            if (channelsBuilder_.isEmpty()) {
              channelsBuilder_.dispose();
              channelsBuilder_ = null;
              channels_ = other.channels_;
              bitField0_ = (bitField0_ & ~0x00000001);
              channelsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getChannelsFieldBuilder() : null;
            } else {
              channelsBuilder_.addAllMessages(other.channels_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getChannelsCount(); i++) {
          if (!getChannels(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .paymentchannels.StoredClientPaymentChannel channels = 1;
      private java.util.List<org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel> channels_ =
        java.util.Collections.emptyList();
      private void ensureChannelsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          channels_ = new java.util.ArrayList<org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel>(channels_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel, org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.Builder, org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannelOrBuilder> channelsBuilder_;

      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public java.util.List<org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel> getChannelsList() {
        if (channelsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(channels_);
        } else {
          return channelsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public int getChannelsCount() {
        if (channelsBuilder_ == null) {
          return channels_.size();
        } else {
          return channelsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel getChannels(int index) {
        if (channelsBuilder_ == null) {
          return channels_.get(index);
        } else {
          return channelsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public Builder setChannels(
          int index, org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel value) {
        if (channelsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChannelsIsMutable();
          channels_.set(index, value);
          onChanged();
        } else {
          channelsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public Builder setChannels(
          int index, org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.Builder builderForValue) {
        if (channelsBuilder_ == null) {
          ensureChannelsIsMutable();
          channels_.set(index, builderForValue.build());
          onChanged();
        } else {
          channelsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public Builder addChannels(org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel value) {
        if (channelsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChannelsIsMutable();
          channels_.add(value);
          onChanged();
        } else {
          channelsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public Builder addChannels(
          int index, org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel value) {
        if (channelsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChannelsIsMutable();
          channels_.add(index, value);
          onChanged();
        } else {
          channelsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public Builder addChannels(
          org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.Builder builderForValue) {
        if (channelsBuilder_ == null) {
          ensureChannelsIsMutable();
          channels_.add(builderForValue.build());
          onChanged();
        } else {
          channelsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public Builder addChannels(
          int index, org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.Builder builderForValue) {
        if (channelsBuilder_ == null) {
          ensureChannelsIsMutable();
          channels_.add(index, builderForValue.build());
          onChanged();
        } else {
          channelsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public Builder addAllChannels(
          java.lang.Iterable<? extends org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel> values) {
        if (channelsBuilder_ == null) {
          ensureChannelsIsMutable();
          super.addAll(values, channels_);
          onChanged();
        } else {
          channelsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public Builder clearChannels() {
        if (channelsBuilder_ == null) {
          channels_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          channelsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public Builder removeChannels(int index) {
        if (channelsBuilder_ == null) {
          ensureChannelsIsMutable();
          channels_.remove(index);
          onChanged();
        } else {
          channelsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.Builder getChannelsBuilder(
          int index) {
        return getChannelsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannelOrBuilder getChannelsOrBuilder(
          int index) {
        if (channelsBuilder_ == null) {
          return channels_.get(index);  } else {
          return channelsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public java.util.List<? extends org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannelOrBuilder> 
           getChannelsOrBuilderList() {
        if (channelsBuilder_ != null) {
          return channelsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(channels_);
        }
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.Builder addChannelsBuilder() {
        return getChannelsFieldBuilder().addBuilder(
            org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.getDefaultInstance());
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.Builder addChannelsBuilder(
          int index) {
        return getChannelsFieldBuilder().addBuilder(
            index, org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.getDefaultInstance());
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public java.util.List<org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.Builder> 
           getChannelsBuilderList() {
        return getChannelsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel, org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.Builder, org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannelOrBuilder> 
          getChannelsFieldBuilder() {
        if (channelsBuilder_ == null) {
          channelsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel, org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.Builder, org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannelOrBuilder>(
                  channels_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          channels_ = null;
        }
        return channelsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:paymentchannels.StoredClientPaymentChannels)
    }

    static {
      defaultInstance = new StoredClientPaymentChannels(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:paymentchannels.StoredClientPaymentChannels)
  }

  public interface StoredClientPaymentChannelOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bytes id = 1;
    /**
     * <code>required bytes id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required bytes id = 1;</code>
     */
    com.google.protobuf.ByteString getId();

    // required bytes contractTransaction = 2;
    /**
     * <code>required bytes contractTransaction = 2;</code>
     */
    boolean hasContractTransaction();
    /**
     * <code>required bytes contractTransaction = 2;</code>
     */
    com.google.protobuf.ByteString getContractTransaction();

    // required bytes refundTransaction = 3;
    /**
     * <code>required bytes refundTransaction = 3;</code>
     */
    boolean hasRefundTransaction();
    /**
     * <code>required bytes refundTransaction = 3;</code>
     */
    com.google.protobuf.ByteString getRefundTransaction();

    // required bytes myPublicKey = 8;
    /**
     * <code>required bytes myPublicKey = 8;</code>
     */
    boolean hasMyPublicKey();
    /**
     * <code>required bytes myPublicKey = 8;</code>
     */
    com.google.protobuf.ByteString getMyPublicKey();

    // required bytes myKey = 4;
    /**
     * <code>required bytes myKey = 4;</code>
     *
     * <pre>
     * Deprecated, key is already stored in the wallet, and found using myPublicKey;
     * </pre>
     */
    boolean hasMyKey();
    /**
     * <code>required bytes myKey = 4;</code>
     *
     * <pre>
     * Deprecated, key is already stored in the wallet, and found using myPublicKey;
     * </pre>
     */
    com.google.protobuf.ByteString getMyKey();

    // required uint64 valueToMe = 5;
    /**
     * <code>required uint64 valueToMe = 5;</code>
     */
    boolean hasValueToMe();
    /**
     * <code>required uint64 valueToMe = 5;</code>
     */
    long getValueToMe();

    // required uint64 refundFees = 6;
    /**
     * <code>required uint64 refundFees = 6;</code>
     */
    boolean hasRefundFees();
    /**
     * <code>required uint64 refundFees = 6;</code>
     */
    long getRefundFees();

    // optional bytes closeTransactionHash = 7;
    /**
     * <code>optional bytes closeTransactionHash = 7;</code>
     *
     * <pre>
     * When set, the hash of the transaction that was presented by the server for closure of the channel.
     * It spends the contractTransaction and is expected to be broadcast to the network by the server.
     * It's supposed to be in the wallet already.
     * </pre>
     */
    boolean hasCloseTransactionHash();
    /**
     * <code>optional bytes closeTransactionHash = 7;</code>
     *
     * <pre>
     * When set, the hash of the transaction that was presented by the server for closure of the channel.
     * It spends the contractTransaction and is expected to be broadcast to the network by the server.
     * It's supposed to be in the wallet already.
     * </pre>
     */
    com.google.protobuf.ByteString getCloseTransactionHash();
  }
  /**
   * Protobuf type {@code paymentchannels.StoredClientPaymentChannel}
   *
   * <pre>
   * A client-side payment channel in serialized form, which can be reloaded later if the client restarts and wants to
   * reopen an existing channel
   * </pre>
   */
  public static final class StoredClientPaymentChannel extends
      com.google.protobuf.GeneratedMessage
      implements StoredClientPaymentChannelOrBuilder {
    // Use StoredClientPaymentChannel.newBuilder() to construct.
    private StoredClientPaymentChannel(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StoredClientPaymentChannel(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StoredClientPaymentChannel defaultInstance;
    public static StoredClientPaymentChannel getDefaultInstance() {
      return defaultInstance;
    }

    public StoredClientPaymentChannel getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StoredClientPaymentChannel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              contractTransaction_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              refundTransaction_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000010;
              myKey_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000020;
              valueToMe_ = input.readUInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000040;
              refundFees_ = input.readUInt64();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000080;
              closeTransactionHash_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000008;
              myPublicKey_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bitcoinj.protocols.channels.ClientState.internal_static_paymentchannels_StoredClientPaymentChannel_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bitcoinj.protocols.channels.ClientState.internal_static_paymentchannels_StoredClientPaymentChannel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.class, org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.Builder.class);
    }

    public static com.google.protobuf.Parser<StoredClientPaymentChannel> PARSER =
        new com.google.protobuf.AbstractParser<StoredClientPaymentChannel>() {
      public StoredClientPaymentChannel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StoredClientPaymentChannel(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StoredClientPaymentChannel> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bytes id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString id_;
    /**
     * <code>required bytes id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes id = 1;</code>
     */
    public com.google.protobuf.ByteString getId() {
      return id_;
    }

    // required bytes contractTransaction = 2;
    public static final int CONTRACTTRANSACTION_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString contractTransaction_;
    /**
     * <code>required bytes contractTransaction = 2;</code>
     */
    public boolean hasContractTransaction() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes contractTransaction = 2;</code>
     */
    public com.google.protobuf.ByteString getContractTransaction() {
      return contractTransaction_;
    }

    // required bytes refundTransaction = 3;
    public static final int REFUNDTRANSACTION_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString refundTransaction_;
    /**
     * <code>required bytes refundTransaction = 3;</code>
     */
    public boolean hasRefundTransaction() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes refundTransaction = 3;</code>
     */
    public com.google.protobuf.ByteString getRefundTransaction() {
      return refundTransaction_;
    }

    // required bytes myPublicKey = 8;
    public static final int MYPUBLICKEY_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString myPublicKey_;
    /**
     * <code>required bytes myPublicKey = 8;</code>
     */
    public boolean hasMyPublicKey() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes myPublicKey = 8;</code>
     */
    public com.google.protobuf.ByteString getMyPublicKey() {
      return myPublicKey_;
    }

    // required bytes myKey = 4;
    public static final int MYKEY_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString myKey_;
    /**
     * <code>required bytes myKey = 4;</code>
     *
     * <pre>
     * Deprecated, key is already stored in the wallet, and found using myPublicKey;
     * </pre>
     */
    public boolean hasMyKey() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required bytes myKey = 4;</code>
     *
     * <pre>
     * Deprecated, key is already stored in the wallet, and found using myPublicKey;
     * </pre>
     */
    public com.google.protobuf.ByteString getMyKey() {
      return myKey_;
    }

    // required uint64 valueToMe = 5;
    public static final int VALUETOME_FIELD_NUMBER = 5;
    private long valueToMe_;
    /**
     * <code>required uint64 valueToMe = 5;</code>
     */
    public boolean hasValueToMe() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required uint64 valueToMe = 5;</code>
     */
    public long getValueToMe() {
      return valueToMe_;
    }

    // required uint64 refundFees = 6;
    public static final int REFUNDFEES_FIELD_NUMBER = 6;
    private long refundFees_;
    /**
     * <code>required uint64 refundFees = 6;</code>
     */
    public boolean hasRefundFees() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required uint64 refundFees = 6;</code>
     */
    public long getRefundFees() {
      return refundFees_;
    }

    // optional bytes closeTransactionHash = 7;
    public static final int CLOSETRANSACTIONHASH_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString closeTransactionHash_;
    /**
     * <code>optional bytes closeTransactionHash = 7;</code>
     *
     * <pre>
     * When set, the hash of the transaction that was presented by the server for closure of the channel.
     * It spends the contractTransaction and is expected to be broadcast to the network by the server.
     * It's supposed to be in the wallet already.
     * </pre>
     */
    public boolean hasCloseTransactionHash() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional bytes closeTransactionHash = 7;</code>
     *
     * <pre>
     * When set, the hash of the transaction that was presented by the server for closure of the channel.
     * It spends the contractTransaction and is expected to be broadcast to the network by the server.
     * It's supposed to be in the wallet already.
     * </pre>
     */
    public com.google.protobuf.ByteString getCloseTransactionHash() {
      return closeTransactionHash_;
    }

    private void initFields() {
      id_ = com.google.protobuf.ByteString.EMPTY;
      contractTransaction_ = com.google.protobuf.ByteString.EMPTY;
      refundTransaction_ = com.google.protobuf.ByteString.EMPTY;
      myPublicKey_ = com.google.protobuf.ByteString.EMPTY;
      myKey_ = com.google.protobuf.ByteString.EMPTY;
      valueToMe_ = 0L;
      refundFees_ = 0L;
      closeTransactionHash_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContractTransaction()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRefundTransaction()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMyPublicKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMyKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValueToMe()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRefundFees()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, contractTransaction_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, refundTransaction_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(4, myKey_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt64(5, valueToMe_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt64(6, refundFees_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(7, closeTransactionHash_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(8, myPublicKey_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, contractTransaction_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, refundTransaction_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, myKey_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, valueToMe_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, refundFees_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, closeTransactionHash_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, myPublicKey_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code paymentchannels.StoredClientPaymentChannel}
     *
     * <pre>
     * A client-side payment channel in serialized form, which can be reloaded later if the client restarts and wants to
     * reopen an existing channel
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.bitcoinj.protocols.channels.ClientState.internal_static_paymentchannels_StoredClientPaymentChannel_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.bitcoinj.protocols.channels.ClientState.internal_static_paymentchannels_StoredClientPaymentChannel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.class, org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.Builder.class);
      }

      // Construct using org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        contractTransaction_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        refundTransaction_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        myPublicKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        myKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        valueToMe_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        refundFees_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        closeTransactionHash_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.bitcoinj.protocols.channels.ClientState.internal_static_paymentchannels_StoredClientPaymentChannel_descriptor;
      }

      public org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel getDefaultInstanceForType() {
        return org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.getDefaultInstance();
      }

      public org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel build() {
        org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel buildPartial() {
        org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel result = new org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.contractTransaction_ = contractTransaction_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.refundTransaction_ = refundTransaction_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.myPublicKey_ = myPublicKey_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.myKey_ = myKey_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.valueToMe_ = valueToMe_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.refundFees_ = refundFees_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.closeTransactionHash_ = closeTransactionHash_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel) {
          return mergeFrom((org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel other) {
        if (other == org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasContractTransaction()) {
          setContractTransaction(other.getContractTransaction());
        }
        if (other.hasRefundTransaction()) {
          setRefundTransaction(other.getRefundTransaction());
        }
        if (other.hasMyPublicKey()) {
          setMyPublicKey(other.getMyPublicKey());
        }
        if (other.hasMyKey()) {
          setMyKey(other.getMyKey());
        }
        if (other.hasValueToMe()) {
          setValueToMe(other.getValueToMe());
        }
        if (other.hasRefundFees()) {
          setRefundFees(other.getRefundFees());
        }
        if (other.hasCloseTransactionHash()) {
          setCloseTransactionHash(other.getCloseTransactionHash());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasContractTransaction()) {
          
          return false;
        }
        if (!hasRefundTransaction()) {
          
          return false;
        }
        if (!hasMyPublicKey()) {
          
          return false;
        }
        if (!hasMyKey()) {
          
          return false;
        }
        if (!hasValueToMe()) {
          
          return false;
        }
        if (!hasRefundFees()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bytes id = 1;
      private com.google.protobuf.ByteString id_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes id = 1;</code>
       */
      public com.google.protobuf.ByteString getId() {
        return id_;
      }
      /**
       * <code>required bytes id = 1;</code>
       */
      public Builder setId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }

      // required bytes contractTransaction = 2;
      private com.google.protobuf.ByteString contractTransaction_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes contractTransaction = 2;</code>
       */
      public boolean hasContractTransaction() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes contractTransaction = 2;</code>
       */
      public com.google.protobuf.ByteString getContractTransaction() {
        return contractTransaction_;
      }
      /**
       * <code>required bytes contractTransaction = 2;</code>
       */
      public Builder setContractTransaction(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        contractTransaction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes contractTransaction = 2;</code>
       */
      public Builder clearContractTransaction() {
        bitField0_ = (bitField0_ & ~0x00000002);
        contractTransaction_ = getDefaultInstance().getContractTransaction();
        onChanged();
        return this;
      }

      // required bytes refundTransaction = 3;
      private com.google.protobuf.ByteString refundTransaction_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes refundTransaction = 3;</code>
       */
      public boolean hasRefundTransaction() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes refundTransaction = 3;</code>
       */
      public com.google.protobuf.ByteString getRefundTransaction() {
        return refundTransaction_;
      }
      /**
       * <code>required bytes refundTransaction = 3;</code>
       */
      public Builder setRefundTransaction(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        refundTransaction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes refundTransaction = 3;</code>
       */
      public Builder clearRefundTransaction() {
        bitField0_ = (bitField0_ & ~0x00000004);
        refundTransaction_ = getDefaultInstance().getRefundTransaction();
        onChanged();
        return this;
      }

      // required bytes myPublicKey = 8;
      private com.google.protobuf.ByteString myPublicKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes myPublicKey = 8;</code>
       */
      public boolean hasMyPublicKey() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes myPublicKey = 8;</code>
       */
      public com.google.protobuf.ByteString getMyPublicKey() {
        return myPublicKey_;
      }
      /**
       * <code>required bytes myPublicKey = 8;</code>
       */
      public Builder setMyPublicKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        myPublicKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes myPublicKey = 8;</code>
       */
      public Builder clearMyPublicKey() {
        bitField0_ = (bitField0_ & ~0x00000008);
        myPublicKey_ = getDefaultInstance().getMyPublicKey();
        onChanged();
        return this;
      }

      // required bytes myKey = 4;
      private com.google.protobuf.ByteString myKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes myKey = 4;</code>
       *
       * <pre>
       * Deprecated, key is already stored in the wallet, and found using myPublicKey;
       * </pre>
       */
      public boolean hasMyKey() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required bytes myKey = 4;</code>
       *
       * <pre>
       * Deprecated, key is already stored in the wallet, and found using myPublicKey;
       * </pre>
       */
      public com.google.protobuf.ByteString getMyKey() {
        return myKey_;
      }
      /**
       * <code>required bytes myKey = 4;</code>
       *
       * <pre>
       * Deprecated, key is already stored in the wallet, and found using myPublicKey;
       * </pre>
       */
      public Builder setMyKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        myKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes myKey = 4;</code>
       *
       * <pre>
       * Deprecated, key is already stored in the wallet, and found using myPublicKey;
       * </pre>
       */
      public Builder clearMyKey() {
        bitField0_ = (bitField0_ & ~0x00000010);
        myKey_ = getDefaultInstance().getMyKey();
        onChanged();
        return this;
      }

      // required uint64 valueToMe = 5;
      private long valueToMe_ ;
      /**
       * <code>required uint64 valueToMe = 5;</code>
       */
      public boolean hasValueToMe() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required uint64 valueToMe = 5;</code>
       */
      public long getValueToMe() {
        return valueToMe_;
      }
      /**
       * <code>required uint64 valueToMe = 5;</code>
       */
      public Builder setValueToMe(long value) {
        bitField0_ |= 0x00000020;
        valueToMe_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 valueToMe = 5;</code>
       */
      public Builder clearValueToMe() {
        bitField0_ = (bitField0_ & ~0x00000020);
        valueToMe_ = 0L;
        onChanged();
        return this;
      }

      // required uint64 refundFees = 6;
      private long refundFees_ ;
      /**
       * <code>required uint64 refundFees = 6;</code>
       */
      public boolean hasRefundFees() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required uint64 refundFees = 6;</code>
       */
      public long getRefundFees() {
        return refundFees_;
      }
      /**
       * <code>required uint64 refundFees = 6;</code>
       */
      public Builder setRefundFees(long value) {
        bitField0_ |= 0x00000040;
        refundFees_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 refundFees = 6;</code>
       */
      public Builder clearRefundFees() {
        bitField0_ = (bitField0_ & ~0x00000040);
        refundFees_ = 0L;
        onChanged();
        return this;
      }

      // optional bytes closeTransactionHash = 7;
      private com.google.protobuf.ByteString closeTransactionHash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes closeTransactionHash = 7;</code>
       *
       * <pre>
       * When set, the hash of the transaction that was presented by the server for closure of the channel.
       * It spends the contractTransaction and is expected to be broadcast to the network by the server.
       * It's supposed to be in the wallet already.
       * </pre>
       */
      public boolean hasCloseTransactionHash() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional bytes closeTransactionHash = 7;</code>
       *
       * <pre>
       * When set, the hash of the transaction that was presented by the server for closure of the channel.
       * It spends the contractTransaction and is expected to be broadcast to the network by the server.
       * It's supposed to be in the wallet already.
       * </pre>
       */
      public com.google.protobuf.ByteString getCloseTransactionHash() {
        return closeTransactionHash_;
      }
      /**
       * <code>optional bytes closeTransactionHash = 7;</code>
       *
       * <pre>
       * When set, the hash of the transaction that was presented by the server for closure of the channel.
       * It spends the contractTransaction and is expected to be broadcast to the network by the server.
       * It's supposed to be in the wallet already.
       * </pre>
       */
      public Builder setCloseTransactionHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        closeTransactionHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes closeTransactionHash = 7;</code>
       *
       * <pre>
       * When set, the hash of the transaction that was presented by the server for closure of the channel.
       * It spends the contractTransaction and is expected to be broadcast to the network by the server.
       * It's supposed to be in the wallet already.
       * </pre>
       */
      public Builder clearCloseTransactionHash() {
        bitField0_ = (bitField0_ & ~0x00000080);
        closeTransactionHash_ = getDefaultInstance().getCloseTransactionHash();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:paymentchannels.StoredClientPaymentChannel)
    }

    static {
      defaultInstance = new StoredClientPaymentChannel(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:paymentchannels.StoredClientPaymentChannel)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_paymentchannels_StoredClientPaymentChannels_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_paymentchannels_StoredClientPaymentChannels_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_paymentchannels_StoredClientPaymentChannel_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_paymentchannels_StoredClientPaymentChannel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n storedclientpaymentchannel.proto\022\017paym" +
      "entchannels\"\\\n\033StoredClientPaymentChanne" +
      "ls\022=\n\010channels\030\001 \003(\0132+.paymentchannels.S" +
      "toredClientPaymentChannel\"\311\001\n\032StoredClie" +
      "ntPaymentChannel\022\n\n\002id\030\001 \002(\014\022\033\n\023contract" +
      "Transaction\030\002 \002(\014\022\031\n\021refundTransaction\030\003" +
      " \002(\014\022\023\n\013myPublicKey\030\010 \002(\014\022\r\n\005myKey\030\004 \002(\014" +
      "\022\021\n\tvalueToMe\030\005 \002(\004\022\022\n\nrefundFees\030\006 \002(\004\022" +
      "\034\n\024closeTransactionHash\030\007 \001(\014B.\n\037org.bit" +
      "coinj.protocols.channelsB\013ClientState"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_paymentchannels_StoredClientPaymentChannels_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_paymentchannels_StoredClientPaymentChannels_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_paymentchannels_StoredClientPaymentChannels_descriptor,
              new java.lang.String[] { "Channels", });
          internal_static_paymentchannels_StoredClientPaymentChannel_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_paymentchannels_StoredClientPaymentChannel_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_paymentchannels_StoredClientPaymentChannel_descriptor,
              new java.lang.String[] { "Id", "ContractTransaction", "RefundTransaction", "MyPublicKey", "MyKey", "ValueToMe", "RefundFees", "CloseTransactionHash", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
