// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: peerseeds.proto

package org.bitcoin.crawler;

public final class PeerSeedProtos {
  private PeerSeedProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PeerSeedDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.bitcoin.crawler.PeerSeedData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string ip_address = 1;</code>
     */
    boolean hasIpAddress();
    /**
     * <code>required string ip_address = 1;</code>
     */
    java.lang.String getIpAddress();
    /**
     * <code>required string ip_address = 1;</code>
     */
    com.google.protobuf.ByteString
        getIpAddressBytes();

    /**
     * <code>required uint32 port = 2;</code>
     */
    boolean hasPort();
    /**
     * <code>required uint32 port = 2;</code>
     */
    int getPort();

    /**
     * <code>required uint32 services = 3;</code>
     */
    boolean hasServices();
    /**
     * <code>required uint32 services = 3;</code>
     */
    int getServices();
  }
  /**
   * Protobuf type {@code org.bitcoin.crawler.PeerSeedData}
   */
  public static final class PeerSeedData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.bitcoin.crawler.PeerSeedData)
      PeerSeedDataOrBuilder {
    // Use PeerSeedData.newBuilder() to construct.
    private PeerSeedData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PeerSeedData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PeerSeedData defaultInstance;
    public static PeerSeedData getDefaultInstance() {
      return defaultInstance;
    }

    public PeerSeedData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PeerSeedData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              ipAddress_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              port_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              services_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bitcoin.crawler.PeerSeedProtos.internal_static_org_bitcoin_crawler_PeerSeedData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bitcoin.crawler.PeerSeedProtos.internal_static_org_bitcoin_crawler_PeerSeedData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.bitcoin.crawler.PeerSeedProtos.PeerSeedData.class, org.bitcoin.crawler.PeerSeedProtos.PeerSeedData.Builder.class);
    }

    public static com.google.protobuf.Parser<PeerSeedData> PARSER =
        new com.google.protobuf.AbstractParser<PeerSeedData>() {
      public PeerSeedData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PeerSeedData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PeerSeedData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int IP_ADDRESS_FIELD_NUMBER = 1;
    private java.lang.Object ipAddress_;
    /**
     * <code>required string ip_address = 1;</code>
     */
    public boolean hasIpAddress() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string ip_address = 1;</code>
     */
    public java.lang.String getIpAddress() {
      java.lang.Object ref = ipAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ipAddress_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ip_address = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIpAddressBytes() {
      java.lang.Object ref = ipAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ipAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 2;
    private int port_;
    /**
     * <code>required uint32 port = 2;</code>
     */
    public boolean hasPort() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 port = 2;</code>
     */
    public int getPort() {
      return port_;
    }

    public static final int SERVICES_FIELD_NUMBER = 3;
    private int services_;
    /**
     * <code>required uint32 services = 3;</code>
     */
    public boolean hasServices() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint32 services = 3;</code>
     */
    public int getServices() {
      return services_;
    }

    private void initFields() {
      ipAddress_ = "";
      port_ = 0;
      services_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasIpAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServices()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIpAddressBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, port_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, services_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIpAddressBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, port_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, services_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeedData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeedData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeedData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeedData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeedData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeedData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeedData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeedData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeedData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeedData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.bitcoin.crawler.PeerSeedProtos.PeerSeedData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.bitcoin.crawler.PeerSeedData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.bitcoin.crawler.PeerSeedData)
        org.bitcoin.crawler.PeerSeedProtos.PeerSeedDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.bitcoin.crawler.PeerSeedProtos.internal_static_org_bitcoin_crawler_PeerSeedData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.bitcoin.crawler.PeerSeedProtos.internal_static_org_bitcoin_crawler_PeerSeedData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.bitcoin.crawler.PeerSeedProtos.PeerSeedData.class, org.bitcoin.crawler.PeerSeedProtos.PeerSeedData.Builder.class);
      }

      // Construct using org.bitcoin.crawler.PeerSeedProtos.PeerSeedData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ipAddress_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        services_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.bitcoin.crawler.PeerSeedProtos.internal_static_org_bitcoin_crawler_PeerSeedData_descriptor;
      }

      public org.bitcoin.crawler.PeerSeedProtos.PeerSeedData getDefaultInstanceForType() {
        return org.bitcoin.crawler.PeerSeedProtos.PeerSeedData.getDefaultInstance();
      }

      public org.bitcoin.crawler.PeerSeedProtos.PeerSeedData build() {
        org.bitcoin.crawler.PeerSeedProtos.PeerSeedData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.bitcoin.crawler.PeerSeedProtos.PeerSeedData buildPartial() {
        org.bitcoin.crawler.PeerSeedProtos.PeerSeedData result = new org.bitcoin.crawler.PeerSeedProtos.PeerSeedData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ipAddress_ = ipAddress_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.port_ = port_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.services_ = services_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.bitcoin.crawler.PeerSeedProtos.PeerSeedData) {
          return mergeFrom((org.bitcoin.crawler.PeerSeedProtos.PeerSeedData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.bitcoin.crawler.PeerSeedProtos.PeerSeedData other) {
        if (other == org.bitcoin.crawler.PeerSeedProtos.PeerSeedData.getDefaultInstance()) return this;
        if (other.hasIpAddress()) {
          bitField0_ |= 0x00000001;
          ipAddress_ = other.ipAddress_;
          onChanged();
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        if (other.hasServices()) {
          setServices(other.getServices());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIpAddress()) {
          
          return false;
        }
        if (!hasPort()) {
          
          return false;
        }
        if (!hasServices()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.bitcoin.crawler.PeerSeedProtos.PeerSeedData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.bitcoin.crawler.PeerSeedProtos.PeerSeedData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object ipAddress_ = "";
      /**
       * <code>required string ip_address = 1;</code>
       */
      public boolean hasIpAddress() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string ip_address = 1;</code>
       */
      public java.lang.String getIpAddress() {
        java.lang.Object ref = ipAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ipAddress_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ip_address = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIpAddressBytes() {
        java.lang.Object ref = ipAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ipAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ip_address = 1;</code>
       */
      public Builder setIpAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ipAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ip_address = 1;</code>
       */
      public Builder clearIpAddress() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ipAddress_ = getDefaultInstance().getIpAddress();
        onChanged();
        return this;
      }
      /**
       * <code>required string ip_address = 1;</code>
       */
      public Builder setIpAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ipAddress_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>required uint32 port = 2;</code>
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 port = 2;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>required uint32 port = 2;</code>
       */
      public Builder setPort(int value) {
        bitField0_ |= 0x00000002;
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 port = 2;</code>
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000002);
        port_ = 0;
        onChanged();
        return this;
      }

      private int services_ ;
      /**
       * <code>required uint32 services = 3;</code>
       */
      public boolean hasServices() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint32 services = 3;</code>
       */
      public int getServices() {
        return services_;
      }
      /**
       * <code>required uint32 services = 3;</code>
       */
      public Builder setServices(int value) {
        bitField0_ |= 0x00000004;
        services_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 services = 3;</code>
       */
      public Builder clearServices() {
        bitField0_ = (bitField0_ & ~0x00000004);
        services_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.bitcoin.crawler.PeerSeedData)
    }

    static {
      defaultInstance = new PeerSeedData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.bitcoin.crawler.PeerSeedData)
  }

  public interface PeerSeedsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.bitcoin.crawler.PeerSeeds)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
     */
    java.util.List<org.bitcoin.crawler.PeerSeedProtos.PeerSeedData> 
        getSeedList();
    /**
     * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
     */
    org.bitcoin.crawler.PeerSeedProtos.PeerSeedData getSeed(int index);
    /**
     * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
     */
    int getSeedCount();
    /**
     * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
     */
    java.util.List<? extends org.bitcoin.crawler.PeerSeedProtos.PeerSeedDataOrBuilder> 
        getSeedOrBuilderList();
    /**
     * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
     */
    org.bitcoin.crawler.PeerSeedProtos.PeerSeedDataOrBuilder getSeedOrBuilder(
        int index);

    /**
     * <code>required uint64 timestamp = 2;</code>
     *
     * <pre>
     * seconds since UNIX epoch
     * </pre>
     */
    boolean hasTimestamp();
    /**
     * <code>required uint64 timestamp = 2;</code>
     *
     * <pre>
     * seconds since UNIX epoch
     * </pre>
     */
    long getTimestamp();

    /**
     * <code>required string net = 3;</code>
     */
    boolean hasNet();
    /**
     * <code>required string net = 3;</code>
     */
    java.lang.String getNet();
    /**
     * <code>required string net = 3;</code>
     */
    com.google.protobuf.ByteString
        getNetBytes();
  }
  /**
   * Protobuf type {@code org.bitcoin.crawler.PeerSeeds}
   */
  public static final class PeerSeeds extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.bitcoin.crawler.PeerSeeds)
      PeerSeedsOrBuilder {
    // Use PeerSeeds.newBuilder() to construct.
    private PeerSeeds(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PeerSeeds(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PeerSeeds defaultInstance;
    public static PeerSeeds getDefaultInstance() {
      return defaultInstance;
    }

    public PeerSeeds getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PeerSeeds(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                seed_ = new java.util.ArrayList<org.bitcoin.crawler.PeerSeedProtos.PeerSeedData>();
                mutable_bitField0_ |= 0x00000001;
              }
              seed_.add(input.readMessage(org.bitcoin.crawler.PeerSeedProtos.PeerSeedData.PARSER, extensionRegistry));
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              timestamp_ = input.readUInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              net_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          seed_ = java.util.Collections.unmodifiableList(seed_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bitcoin.crawler.PeerSeedProtos.internal_static_org_bitcoin_crawler_PeerSeeds_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bitcoin.crawler.PeerSeedProtos.internal_static_org_bitcoin_crawler_PeerSeeds_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.bitcoin.crawler.PeerSeedProtos.PeerSeeds.class, org.bitcoin.crawler.PeerSeedProtos.PeerSeeds.Builder.class);
    }

    public static com.google.protobuf.Parser<PeerSeeds> PARSER =
        new com.google.protobuf.AbstractParser<PeerSeeds>() {
      public PeerSeeds parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PeerSeeds(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PeerSeeds> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SEED_FIELD_NUMBER = 1;
    private java.util.List<org.bitcoin.crawler.PeerSeedProtos.PeerSeedData> seed_;
    /**
     * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
     */
    public java.util.List<org.bitcoin.crawler.PeerSeedProtos.PeerSeedData> getSeedList() {
      return seed_;
    }
    /**
     * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
     */
    public java.util.List<? extends org.bitcoin.crawler.PeerSeedProtos.PeerSeedDataOrBuilder> 
        getSeedOrBuilderList() {
      return seed_;
    }
    /**
     * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
     */
    public int getSeedCount() {
      return seed_.size();
    }
    /**
     * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
     */
    public org.bitcoin.crawler.PeerSeedProtos.PeerSeedData getSeed(int index) {
      return seed_.get(index);
    }
    /**
     * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
     */
    public org.bitcoin.crawler.PeerSeedProtos.PeerSeedDataOrBuilder getSeedOrBuilder(
        int index) {
      return seed_.get(index);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <code>required uint64 timestamp = 2;</code>
     *
     * <pre>
     * seconds since UNIX epoch
     * </pre>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 timestamp = 2;</code>
     *
     * <pre>
     * seconds since UNIX epoch
     * </pre>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int NET_FIELD_NUMBER = 3;
    private java.lang.Object net_;
    /**
     * <code>required string net = 3;</code>
     */
    public boolean hasNet() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string net = 3;</code>
     */
    public java.lang.String getNet() {
      java.lang.Object ref = net_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          net_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string net = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNetBytes() {
      java.lang.Object ref = net_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        net_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      seed_ = java.util.Collections.emptyList();
      timestamp_ = 0L;
      net_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNet()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getSeedCount(); i++) {
        if (!getSeed(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < seed_.size(); i++) {
        output.writeMessage(1, seed_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(2, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, getNetBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < seed_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, seed_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNetBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeeds parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeeds parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeeds parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeeds parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeeds parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeeds parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeeds parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeeds parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeeds parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeeds parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.bitcoin.crawler.PeerSeedProtos.PeerSeeds prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.bitcoin.crawler.PeerSeeds}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.bitcoin.crawler.PeerSeeds)
        org.bitcoin.crawler.PeerSeedProtos.PeerSeedsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.bitcoin.crawler.PeerSeedProtos.internal_static_org_bitcoin_crawler_PeerSeeds_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.bitcoin.crawler.PeerSeedProtos.internal_static_org_bitcoin_crawler_PeerSeeds_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.bitcoin.crawler.PeerSeedProtos.PeerSeeds.class, org.bitcoin.crawler.PeerSeedProtos.PeerSeeds.Builder.class);
      }

      // Construct using org.bitcoin.crawler.PeerSeedProtos.PeerSeeds.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSeedFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (seedBuilder_ == null) {
          seed_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          seedBuilder_.clear();
        }
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        net_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.bitcoin.crawler.PeerSeedProtos.internal_static_org_bitcoin_crawler_PeerSeeds_descriptor;
      }

      public org.bitcoin.crawler.PeerSeedProtos.PeerSeeds getDefaultInstanceForType() {
        return org.bitcoin.crawler.PeerSeedProtos.PeerSeeds.getDefaultInstance();
      }

      public org.bitcoin.crawler.PeerSeedProtos.PeerSeeds build() {
        org.bitcoin.crawler.PeerSeedProtos.PeerSeeds result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.bitcoin.crawler.PeerSeedProtos.PeerSeeds buildPartial() {
        org.bitcoin.crawler.PeerSeedProtos.PeerSeeds result = new org.bitcoin.crawler.PeerSeedProtos.PeerSeeds(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (seedBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            seed_ = java.util.Collections.unmodifiableList(seed_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.seed_ = seed_;
        } else {
          result.seed_ = seedBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.net_ = net_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.bitcoin.crawler.PeerSeedProtos.PeerSeeds) {
          return mergeFrom((org.bitcoin.crawler.PeerSeedProtos.PeerSeeds)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.bitcoin.crawler.PeerSeedProtos.PeerSeeds other) {
        if (other == org.bitcoin.crawler.PeerSeedProtos.PeerSeeds.getDefaultInstance()) return this;
        if (seedBuilder_ == null) {
          if (!other.seed_.isEmpty()) {
            if (seed_.isEmpty()) {
              seed_ = other.seed_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSeedIsMutable();
              seed_.addAll(other.seed_);
            }
            onChanged();
          }
        } else {
          if (!other.seed_.isEmpty()) {
            if (seedBuilder_.isEmpty()) {
              seedBuilder_.dispose();
              seedBuilder_ = null;
              seed_ = other.seed_;
              bitField0_ = (bitField0_ & ~0x00000001);
              seedBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSeedFieldBuilder() : null;
            } else {
              seedBuilder_.addAllMessages(other.seed_);
            }
          }
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasNet()) {
          bitField0_ |= 0x00000004;
          net_ = other.net_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTimestamp()) {
          
          return false;
        }
        if (!hasNet()) {
          
          return false;
        }
        for (int i = 0; i < getSeedCount(); i++) {
          if (!getSeed(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.bitcoin.crawler.PeerSeedProtos.PeerSeeds parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.bitcoin.crawler.PeerSeedProtos.PeerSeeds) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.bitcoin.crawler.PeerSeedProtos.PeerSeedData> seed_ =
        java.util.Collections.emptyList();
      private void ensureSeedIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          seed_ = new java.util.ArrayList<org.bitcoin.crawler.PeerSeedProtos.PeerSeedData>(seed_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.bitcoin.crawler.PeerSeedProtos.PeerSeedData, org.bitcoin.crawler.PeerSeedProtos.PeerSeedData.Builder, org.bitcoin.crawler.PeerSeedProtos.PeerSeedDataOrBuilder> seedBuilder_;

      /**
       * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
       */
      public java.util.List<org.bitcoin.crawler.PeerSeedProtos.PeerSeedData> getSeedList() {
        if (seedBuilder_ == null) {
          return java.util.Collections.unmodifiableList(seed_);
        } else {
          return seedBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
       */
      public int getSeedCount() {
        if (seedBuilder_ == null) {
          return seed_.size();
        } else {
          return seedBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
       */
      public org.bitcoin.crawler.PeerSeedProtos.PeerSeedData getSeed(int index) {
        if (seedBuilder_ == null) {
          return seed_.get(index);
        } else {
          return seedBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
       */
      public Builder setSeed(
          int index, org.bitcoin.crawler.PeerSeedProtos.PeerSeedData value) {
        if (seedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSeedIsMutable();
          seed_.set(index, value);
          onChanged();
        } else {
          seedBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
       */
      public Builder setSeed(
          int index, org.bitcoin.crawler.PeerSeedProtos.PeerSeedData.Builder builderForValue) {
        if (seedBuilder_ == null) {
          ensureSeedIsMutable();
          seed_.set(index, builderForValue.build());
          onChanged();
        } else {
          seedBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
       */
      public Builder addSeed(org.bitcoin.crawler.PeerSeedProtos.PeerSeedData value) {
        if (seedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSeedIsMutable();
          seed_.add(value);
          onChanged();
        } else {
          seedBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
       */
      public Builder addSeed(
          int index, org.bitcoin.crawler.PeerSeedProtos.PeerSeedData value) {
        if (seedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSeedIsMutable();
          seed_.add(index, value);
          onChanged();
        } else {
          seedBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
       */
      public Builder addSeed(
          org.bitcoin.crawler.PeerSeedProtos.PeerSeedData.Builder builderForValue) {
        if (seedBuilder_ == null) {
          ensureSeedIsMutable();
          seed_.add(builderForValue.build());
          onChanged();
        } else {
          seedBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
       */
      public Builder addSeed(
          int index, org.bitcoin.crawler.PeerSeedProtos.PeerSeedData.Builder builderForValue) {
        if (seedBuilder_ == null) {
          ensureSeedIsMutable();
          seed_.add(index, builderForValue.build());
          onChanged();
        } else {
          seedBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
       */
      public Builder addAllSeed(
          java.lang.Iterable<? extends org.bitcoin.crawler.PeerSeedProtos.PeerSeedData> values) {
        if (seedBuilder_ == null) {
          ensureSeedIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, seed_);
          onChanged();
        } else {
          seedBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
       */
      public Builder clearSeed() {
        if (seedBuilder_ == null) {
          seed_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          seedBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
       */
      public Builder removeSeed(int index) {
        if (seedBuilder_ == null) {
          ensureSeedIsMutable();
          seed_.remove(index);
          onChanged();
        } else {
          seedBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
       */
      public org.bitcoin.crawler.PeerSeedProtos.PeerSeedData.Builder getSeedBuilder(
          int index) {
        return getSeedFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
       */
      public org.bitcoin.crawler.PeerSeedProtos.PeerSeedDataOrBuilder getSeedOrBuilder(
          int index) {
        if (seedBuilder_ == null) {
          return seed_.get(index);  } else {
          return seedBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
       */
      public java.util.List<? extends org.bitcoin.crawler.PeerSeedProtos.PeerSeedDataOrBuilder> 
           getSeedOrBuilderList() {
        if (seedBuilder_ != null) {
          return seedBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(seed_);
        }
      }
      /**
       * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
       */
      public org.bitcoin.crawler.PeerSeedProtos.PeerSeedData.Builder addSeedBuilder() {
        return getSeedFieldBuilder().addBuilder(
            org.bitcoin.crawler.PeerSeedProtos.PeerSeedData.getDefaultInstance());
      }
      /**
       * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
       */
      public org.bitcoin.crawler.PeerSeedProtos.PeerSeedData.Builder addSeedBuilder(
          int index) {
        return getSeedFieldBuilder().addBuilder(
            index, org.bitcoin.crawler.PeerSeedProtos.PeerSeedData.getDefaultInstance());
      }
      /**
       * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
       */
      public java.util.List<org.bitcoin.crawler.PeerSeedProtos.PeerSeedData.Builder> 
           getSeedBuilderList() {
        return getSeedFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.bitcoin.crawler.PeerSeedProtos.PeerSeedData, org.bitcoin.crawler.PeerSeedProtos.PeerSeedData.Builder, org.bitcoin.crawler.PeerSeedProtos.PeerSeedDataOrBuilder> 
          getSeedFieldBuilder() {
        if (seedBuilder_ == null) {
          seedBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.bitcoin.crawler.PeerSeedProtos.PeerSeedData, org.bitcoin.crawler.PeerSeedProtos.PeerSeedData.Builder, org.bitcoin.crawler.PeerSeedProtos.PeerSeedDataOrBuilder>(
                  seed_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          seed_ = null;
        }
        return seedBuilder_;
      }

      private long timestamp_ ;
      /**
       * <code>required uint64 timestamp = 2;</code>
       *
       * <pre>
       * seconds since UNIX epoch
       * </pre>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint64 timestamp = 2;</code>
       *
       * <pre>
       * seconds since UNIX epoch
       * </pre>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required uint64 timestamp = 2;</code>
       *
       * <pre>
       * seconds since UNIX epoch
       * </pre>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 timestamp = 2;</code>
       *
       * <pre>
       * seconds since UNIX epoch
       * </pre>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object net_ = "";
      /**
       * <code>required string net = 3;</code>
       */
      public boolean hasNet() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string net = 3;</code>
       */
      public java.lang.String getNet() {
        java.lang.Object ref = net_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            net_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string net = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNetBytes() {
        java.lang.Object ref = net_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          net_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string net = 3;</code>
       */
      public Builder setNet(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        net_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string net = 3;</code>
       */
      public Builder clearNet() {
        bitField0_ = (bitField0_ & ~0x00000004);
        net_ = getDefaultInstance().getNet();
        onChanged();
        return this;
      }
      /**
       * <code>required string net = 3;</code>
       */
      public Builder setNetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        net_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.bitcoin.crawler.PeerSeeds)
    }

    static {
      defaultInstance = new PeerSeeds(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.bitcoin.crawler.PeerSeeds)
  }

  public interface SignedPeerSeedsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.bitcoin.crawler.SignedPeerSeeds)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes peer_seeds = 1;</code>
     */
    boolean hasPeerSeeds();
    /**
     * <code>required bytes peer_seeds = 1;</code>
     */
    com.google.protobuf.ByteString getPeerSeeds();

    /**
     * <code>required bytes signature = 2;</code>
     */
    boolean hasSignature();
    /**
     * <code>required bytes signature = 2;</code>
     */
    com.google.protobuf.ByteString getSignature();

    /**
     * <code>required bytes pubkey = 3;</code>
     */
    boolean hasPubkey();
    /**
     * <code>required bytes pubkey = 3;</code>
     */
    com.google.protobuf.ByteString getPubkey();
  }
  /**
   * Protobuf type {@code org.bitcoin.crawler.SignedPeerSeeds}
   */
  public static final class SignedPeerSeeds extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.bitcoin.crawler.SignedPeerSeeds)
      SignedPeerSeedsOrBuilder {
    // Use SignedPeerSeeds.newBuilder() to construct.
    private SignedPeerSeeds(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SignedPeerSeeds(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SignedPeerSeeds defaultInstance;
    public static SignedPeerSeeds getDefaultInstance() {
      return defaultInstance;
    }

    public SignedPeerSeeds getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SignedPeerSeeds(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              peerSeeds_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              signature_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              pubkey_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bitcoin.crawler.PeerSeedProtos.internal_static_org_bitcoin_crawler_SignedPeerSeeds_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bitcoin.crawler.PeerSeedProtos.internal_static_org_bitcoin_crawler_SignedPeerSeeds_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds.class, org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds.Builder.class);
    }

    public static com.google.protobuf.Parser<SignedPeerSeeds> PARSER =
        new com.google.protobuf.AbstractParser<SignedPeerSeeds>() {
      public SignedPeerSeeds parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SignedPeerSeeds(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SignedPeerSeeds> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PEER_SEEDS_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString peerSeeds_;
    /**
     * <code>required bytes peer_seeds = 1;</code>
     */
    public boolean hasPeerSeeds() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes peer_seeds = 1;</code>
     */
    public com.google.protobuf.ByteString getPeerSeeds() {
      return peerSeeds_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString signature_;
    /**
     * <code>required bytes signature = 2;</code>
     */
    public boolean hasSignature() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes signature = 2;</code>
     */
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }

    public static final int PUBKEY_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString pubkey_;
    /**
     * <code>required bytes pubkey = 3;</code>
     */
    public boolean hasPubkey() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes pubkey = 3;</code>
     */
    public com.google.protobuf.ByteString getPubkey() {
      return pubkey_;
    }

    private void initFields() {
      peerSeeds_ = com.google.protobuf.ByteString.EMPTY;
      signature_ = com.google.protobuf.ByteString.EMPTY;
      pubkey_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPeerSeeds()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSignature()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPubkey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, peerSeeds_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, signature_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, pubkey_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, peerSeeds_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, signature_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, pubkey_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.bitcoin.crawler.SignedPeerSeeds}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.bitcoin.crawler.SignedPeerSeeds)
        org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeedsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.bitcoin.crawler.PeerSeedProtos.internal_static_org_bitcoin_crawler_SignedPeerSeeds_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.bitcoin.crawler.PeerSeedProtos.internal_static_org_bitcoin_crawler_SignedPeerSeeds_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds.class, org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds.Builder.class);
      }

      // Construct using org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        peerSeeds_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        signature_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        pubkey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.bitcoin.crawler.PeerSeedProtos.internal_static_org_bitcoin_crawler_SignedPeerSeeds_descriptor;
      }

      public org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds getDefaultInstanceForType() {
        return org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds.getDefaultInstance();
      }

      public org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds build() {
        org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds buildPartial() {
        org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds result = new org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.peerSeeds_ = peerSeeds_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.signature_ = signature_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.pubkey_ = pubkey_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds) {
          return mergeFrom((org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds other) {
        if (other == org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds.getDefaultInstance()) return this;
        if (other.hasPeerSeeds()) {
          setPeerSeeds(other.getPeerSeeds());
        }
        if (other.hasSignature()) {
          setSignature(other.getSignature());
        }
        if (other.hasPubkey()) {
          setPubkey(other.getPubkey());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPeerSeeds()) {
          
          return false;
        }
        if (!hasSignature()) {
          
          return false;
        }
        if (!hasPubkey()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString peerSeeds_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes peer_seeds = 1;</code>
       */
      public boolean hasPeerSeeds() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes peer_seeds = 1;</code>
       */
      public com.google.protobuf.ByteString getPeerSeeds() {
        return peerSeeds_;
      }
      /**
       * <code>required bytes peer_seeds = 1;</code>
       */
      public Builder setPeerSeeds(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        peerSeeds_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes peer_seeds = 1;</code>
       */
      public Builder clearPeerSeeds() {
        bitField0_ = (bitField0_ & ~0x00000001);
        peerSeeds_ = getDefaultInstance().getPeerSeeds();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes signature = 2;</code>
       */
      public boolean hasSignature() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes signature = 2;</code>
       */
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      /**
       * <code>required bytes signature = 2;</code>
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes signature = 2;</code>
       */
      public Builder clearSignature() {
        bitField0_ = (bitField0_ & ~0x00000002);
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString pubkey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes pubkey = 3;</code>
       */
      public boolean hasPubkey() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes pubkey = 3;</code>
       */
      public com.google.protobuf.ByteString getPubkey() {
        return pubkey_;
      }
      /**
       * <code>required bytes pubkey = 3;</code>
       */
      public Builder setPubkey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        pubkey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes pubkey = 3;</code>
       */
      public Builder clearPubkey() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pubkey_ = getDefaultInstance().getPubkey();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.bitcoin.crawler.SignedPeerSeeds)
    }

    static {
      defaultInstance = new SignedPeerSeeds(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.bitcoin.crawler.SignedPeerSeeds)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_bitcoin_crawler_PeerSeedData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_bitcoin_crawler_PeerSeedData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_bitcoin_crawler_PeerSeeds_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_bitcoin_crawler_PeerSeeds_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_bitcoin_crawler_SignedPeerSeeds_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_bitcoin_crawler_SignedPeerSeeds_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017peerseeds.proto\022\023org.bitcoin.crawler\"B" +
      "\n\014PeerSeedData\022\022\n\nip_address\030\001 \002(\t\022\014\n\004po" +
      "rt\030\002 \002(\r\022\020\n\010services\030\003 \002(\r\"\\\n\tPeerSeeds\022" +
      "/\n\004seed\030\001 \003(\0132!.org.bitcoin.crawler.Peer" +
      "SeedData\022\021\n\ttimestamp\030\002 \002(\004\022\013\n\003net\030\003 \002(\t" +
      "\"H\n\017SignedPeerSeeds\022\022\n\npeer_seeds\030\001 \002(\014\022" +
      "\021\n\tsignature\030\002 \002(\014\022\016\n\006pubkey\030\003 \002(\014B%\n\023or" +
      "g.bitcoin.crawlerB\016PeerSeedProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_bitcoin_crawler_PeerSeedData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_bitcoin_crawler_PeerSeedData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_bitcoin_crawler_PeerSeedData_descriptor,
        new java.lang.String[] { "IpAddress", "Port", "Services", });
    internal_static_org_bitcoin_crawler_PeerSeeds_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_bitcoin_crawler_PeerSeeds_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_bitcoin_crawler_PeerSeeds_descriptor,
        new java.lang.String[] { "Seed", "Timestamp", "Net", });
    internal_static_org_bitcoin_crawler_SignedPeerSeeds_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_bitcoin_crawler_SignedPeerSeeds_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_bitcoin_crawler_SignedPeerSeeds_descriptor,
        new java.lang.String[] { "PeerSeeds", "Signature", "Pubkey", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
