// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: peerseeds.proto

package org.bitcoin.crawler;

public final class PeerSeedProtos {
  private PeerSeedProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface PeerSeedDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.bitcoin.crawler.PeerSeedData)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required string ip_address = 1;</code>
     * @return Whether the ipAddress field is set.
     */
    boolean hasIpAddress();
    /**
     * <code>required string ip_address = 1;</code>
     * @return The ipAddress.
     */
    java.lang.String getIpAddress();
    /**
     * <code>required string ip_address = 1;</code>
     * @return The bytes for ipAddress.
     */
    com.google.protobuf.ByteString
        getIpAddressBytes();

    /**
     * <code>required uint32 port = 2;</code>
     * @return Whether the port field is set.
     */
    boolean hasPort();
    /**
     * <code>required uint32 port = 2;</code>
     * @return The port.
     */
    int getPort();

    /**
     * <code>required uint32 services = 3;</code>
     * @return Whether the services field is set.
     */
    boolean hasServices();
    /**
     * <code>required uint32 services = 3;</code>
     * @return The services.
     */
    int getServices();
  }
  /**
   * Protobuf type {@code org.bitcoin.crawler.PeerSeedData}
   */
  public  static final class PeerSeedData extends
      com.google.protobuf.GeneratedMessageLite<
          PeerSeedData, PeerSeedData.Builder> implements
      // @@protoc_insertion_point(message_implements:org.bitcoin.crawler.PeerSeedData)
      PeerSeedDataOrBuilder {
    private PeerSeedData() {
      ipAddress_ = "";
    }
    private int bitField0_;
    public static final int IP_ADDRESS_FIELD_NUMBER = 1;
    private java.lang.String ipAddress_;
    /**
     * <code>required string ip_address = 1;</code>
     * @return Whether the ipAddress field is set.
     */
    @java.lang.Override
    public boolean hasIpAddress() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string ip_address = 1;</code>
     * @return The ipAddress.
     */
    @java.lang.Override
    public java.lang.String getIpAddress() {
      return ipAddress_;
    }
    /**
     * <code>required string ip_address = 1;</code>
     * @return The bytes for ipAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIpAddressBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(ipAddress_);
    }
    /**
     * <code>required string ip_address = 1;</code>
     * @param value The ipAddress to set.
     */
    private void setIpAddress(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
      ipAddress_ = value;
    }
    /**
     * <code>required string ip_address = 1;</code>
     */
    private void clearIpAddress() {
      bitField0_ = (bitField0_ & ~0x00000001);
      ipAddress_ = getDefaultInstance().getIpAddress();
    }
    /**
     * <code>required string ip_address = 1;</code>
     * @param value The bytes for ipAddress to set.
     */
    private void setIpAddressBytes(
        com.google.protobuf.ByteString value) {
      ipAddress_ = value.toStringUtf8();
      bitField0_ |= 0x00000001;
    }

    public static final int PORT_FIELD_NUMBER = 2;
    private int port_;
    /**
     * <code>required uint32 port = 2;</code>
     * @return Whether the port field is set.
     */
    @java.lang.Override
    public boolean hasPort() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required uint32 port = 2;</code>
     * @return The port.
     */
    @java.lang.Override
    public int getPort() {
      return port_;
    }
    /**
     * <code>required uint32 port = 2;</code>
     * @param value The port to set.
     */
    private void setPort(int value) {
      bitField0_ |= 0x00000002;
      port_ = value;
    }
    /**
     * <code>required uint32 port = 2;</code>
     */
    private void clearPort() {
      bitField0_ = (bitField0_ & ~0x00000002);
      port_ = 0;
    }

    public static final int SERVICES_FIELD_NUMBER = 3;
    private int services_;
    /**
     * <code>required uint32 services = 3;</code>
     * @return Whether the services field is set.
     */
    @java.lang.Override
    public boolean hasServices() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required uint32 services = 3;</code>
     * @return The services.
     */
    @java.lang.Override
    public int getServices() {
      return services_;
    }
    /**
     * <code>required uint32 services = 3;</code>
     * @param value The services to set.
     */
    private void setServices(int value) {
      bitField0_ |= 0x00000004;
      services_ = value;
    }
    /**
     * <code>required uint32 services = 3;</code>
     */
    private void clearServices() {
      bitField0_ = (bitField0_ & ~0x00000004);
      services_ = 0;
    }

    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeedData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeedData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeedData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeedData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeedData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeedData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeedData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeedData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeedData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeedData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeedData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeedData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(org.bitcoin.crawler.PeerSeedProtos.PeerSeedData prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code org.bitcoin.crawler.PeerSeedData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.bitcoin.crawler.PeerSeedProtos.PeerSeedData, Builder> implements
        // @@protoc_insertion_point(builder_implements:org.bitcoin.crawler.PeerSeedData)
        org.bitcoin.crawler.PeerSeedProtos.PeerSeedDataOrBuilder {
      // Construct using org.bitcoin.crawler.PeerSeedProtos.PeerSeedData.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required string ip_address = 1;</code>
       * @return Whether the ipAddress field is set.
       */
      @java.lang.Override
      public boolean hasIpAddress() {
        return instance.hasIpAddress();
      }
      /**
       * <code>required string ip_address = 1;</code>
       * @return The ipAddress.
       */
      @java.lang.Override
      public java.lang.String getIpAddress() {
        return instance.getIpAddress();
      }
      /**
       * <code>required string ip_address = 1;</code>
       * @return The bytes for ipAddress.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getIpAddressBytes() {
        return instance.getIpAddressBytes();
      }
      /**
       * <code>required string ip_address = 1;</code>
       * @param value The ipAddress to set.
       * @return This builder for chaining.
       */
      public Builder setIpAddress(
          java.lang.String value) {
        copyOnWrite();
        instance.setIpAddress(value);
        return this;
      }
      /**
       * <code>required string ip_address = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIpAddress() {
        copyOnWrite();
        instance.clearIpAddress();
        return this;
      }
      /**
       * <code>required string ip_address = 1;</code>
       * @param value The bytes for ipAddress to set.
       * @return This builder for chaining.
       */
      public Builder setIpAddressBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setIpAddressBytes(value);
        return this;
      }

      /**
       * <code>required uint32 port = 2;</code>
       * @return Whether the port field is set.
       */
      @java.lang.Override
      public boolean hasPort() {
        return instance.hasPort();
      }
      /**
       * <code>required uint32 port = 2;</code>
       * @return The port.
       */
      @java.lang.Override
      public int getPort() {
        return instance.getPort();
      }
      /**
       * <code>required uint32 port = 2;</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(int value) {
        copyOnWrite();
        instance.setPort(value);
        return this;
      }
      /**
       * <code>required uint32 port = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        copyOnWrite();
        instance.clearPort();
        return this;
      }

      /**
       * <code>required uint32 services = 3;</code>
       * @return Whether the services field is set.
       */
      @java.lang.Override
      public boolean hasServices() {
        return instance.hasServices();
      }
      /**
       * <code>required uint32 services = 3;</code>
       * @return The services.
       */
      @java.lang.Override
      public int getServices() {
        return instance.getServices();
      }
      /**
       * <code>required uint32 services = 3;</code>
       * @param value The services to set.
       * @return This builder for chaining.
       */
      public Builder setServices(int value) {
        copyOnWrite();
        instance.setServices(value);
        return this;
      }
      /**
       * <code>required uint32 services = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearServices() {
        copyOnWrite();
        instance.clearServices();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.bitcoin.crawler.PeerSeedData)
    }
    private byte memoizedIsInitialized = 2;
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new org.bitcoin.crawler.PeerSeedProtos.PeerSeedData();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "ipAddress_",
              "port_",
              "services_",
            };
            java.lang.String info =
                "\u0001\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0003\u0001\u1508\u0000\u0002" +
                "\u150b\u0001\u0003\u150b\u0002";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<org.bitcoin.crawler.PeerSeedProtos.PeerSeedData> parser = PARSER;
          if (parser == null) {
            synchronized (org.bitcoin.crawler.PeerSeedProtos.PeerSeedData.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<org.bitcoin.crawler.PeerSeedProtos.PeerSeedData>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:org.bitcoin.crawler.PeerSeedData)
    private static final org.bitcoin.crawler.PeerSeedProtos.PeerSeedData DEFAULT_INSTANCE;
    static {
      PeerSeedData defaultInstance = new PeerSeedData();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        PeerSeedData.class, defaultInstance);
    }

    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeedData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PeerSeedData> PARSER;

    public static com.google.protobuf.Parser<PeerSeedData> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PeerSeedsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.bitcoin.crawler.PeerSeeds)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
     */
    java.util.List<org.bitcoin.crawler.PeerSeedProtos.PeerSeedData> 
        getSeedList();
    /**
     * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
     */
    org.bitcoin.crawler.PeerSeedProtos.PeerSeedData getSeed(int index);
    /**
     * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
     */
    int getSeedCount();

    /**
     * <pre>
     * seconds since UNIX epoch
     * </pre>
     *
     * <code>required uint64 timestamp = 2;</code>
     * @return Whether the timestamp field is set.
     */
    boolean hasTimestamp();
    /**
     * <pre>
     * seconds since UNIX epoch
     * </pre>
     *
     * <code>required uint64 timestamp = 2;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>required string net = 3;</code>
     * @return Whether the net field is set.
     */
    boolean hasNet();
    /**
     * <code>required string net = 3;</code>
     * @return The net.
     */
    java.lang.String getNet();
    /**
     * <code>required string net = 3;</code>
     * @return The bytes for net.
     */
    com.google.protobuf.ByteString
        getNetBytes();
  }
  /**
   * Protobuf type {@code org.bitcoin.crawler.PeerSeeds}
   */
  public  static final class PeerSeeds extends
      com.google.protobuf.GeneratedMessageLite<
          PeerSeeds, PeerSeeds.Builder> implements
      // @@protoc_insertion_point(message_implements:org.bitcoin.crawler.PeerSeeds)
      PeerSeedsOrBuilder {
    private PeerSeeds() {
      seed_ = emptyProtobufList();
      net_ = "";
    }
    private int bitField0_;
    public static final int SEED_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<org.bitcoin.crawler.PeerSeedProtos.PeerSeedData> seed_;
    /**
     * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
     */
    @java.lang.Override
    public java.util.List<org.bitcoin.crawler.PeerSeedProtos.PeerSeedData> getSeedList() {
      return seed_;
    }
    /**
     * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
     */
    public java.util.List<? extends org.bitcoin.crawler.PeerSeedProtos.PeerSeedDataOrBuilder> 
        getSeedOrBuilderList() {
      return seed_;
    }
    /**
     * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
     */
    @java.lang.Override
    public int getSeedCount() {
      return seed_.size();
    }
    /**
     * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
     */
    @java.lang.Override
    public org.bitcoin.crawler.PeerSeedProtos.PeerSeedData getSeed(int index) {
      return seed_.get(index);
    }
    /**
     * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
     */
    public org.bitcoin.crawler.PeerSeedProtos.PeerSeedDataOrBuilder getSeedOrBuilder(
        int index) {
      return seed_.get(index);
    }
    private void ensureSeedIsMutable() {
      com.google.protobuf.Internal.ProtobufList<org.bitcoin.crawler.PeerSeedProtos.PeerSeedData> tmp = seed_;
      if (!tmp.isModifiable()) {
        seed_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
     */
    private void setSeed(
        int index, org.bitcoin.crawler.PeerSeedProtos.PeerSeedData value) {
      value.getClass();
  ensureSeedIsMutable();
      seed_.set(index, value);
    }
    /**
     * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
     */
    private void addSeed(org.bitcoin.crawler.PeerSeedProtos.PeerSeedData value) {
      value.getClass();
  ensureSeedIsMutable();
      seed_.add(value);
    }
    /**
     * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
     */
    private void addSeed(
        int index, org.bitcoin.crawler.PeerSeedProtos.PeerSeedData value) {
      value.getClass();
  ensureSeedIsMutable();
      seed_.add(index, value);
    }
    /**
     * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
     */
    private void addAllSeed(
        java.lang.Iterable<? extends org.bitcoin.crawler.PeerSeedProtos.PeerSeedData> values) {
      ensureSeedIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, seed_);
    }
    /**
     * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
     */
    private void clearSeed() {
      seed_ = emptyProtobufList();
    }
    /**
     * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
     */
    private void removeSeed(int index) {
      ensureSeedIsMutable();
      seed_.remove(index);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <pre>
     * seconds since UNIX epoch
     * </pre>
     *
     * <code>required uint64 timestamp = 2;</code>
     * @return Whether the timestamp field is set.
     */
    @java.lang.Override
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * seconds since UNIX epoch
     * </pre>
     *
     * <code>required uint64 timestamp = 2;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * seconds since UNIX epoch
     * </pre>
     *
     * <code>required uint64 timestamp = 2;</code>
     * @param value The timestamp to set.
     */
    private void setTimestamp(long value) {
      bitField0_ |= 0x00000001;
      timestamp_ = value;
    }
    /**
     * <pre>
     * seconds since UNIX epoch
     * </pre>
     *
     * <code>required uint64 timestamp = 2;</code>
     */
    private void clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000001);
      timestamp_ = 0L;
    }

    public static final int NET_FIELD_NUMBER = 3;
    private java.lang.String net_;
    /**
     * <code>required string net = 3;</code>
     * @return Whether the net field is set.
     */
    @java.lang.Override
    public boolean hasNet() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string net = 3;</code>
     * @return The net.
     */
    @java.lang.Override
    public java.lang.String getNet() {
      return net_;
    }
    /**
     * <code>required string net = 3;</code>
     * @return The bytes for net.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNetBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(net_);
    }
    /**
     * <code>required string net = 3;</code>
     * @param value The net to set.
     */
    private void setNet(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000002;
      net_ = value;
    }
    /**
     * <code>required string net = 3;</code>
     */
    private void clearNet() {
      bitField0_ = (bitField0_ & ~0x00000002);
      net_ = getDefaultInstance().getNet();
    }
    /**
     * <code>required string net = 3;</code>
     * @param value The bytes for net to set.
     */
    private void setNetBytes(
        com.google.protobuf.ByteString value) {
      net_ = value.toStringUtf8();
      bitField0_ |= 0x00000002;
    }

    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeeds parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeeds parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeeds parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeeds parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeeds parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeeds parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeeds parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeeds parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeeds parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeeds parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeeds parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeeds parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(org.bitcoin.crawler.PeerSeedProtos.PeerSeeds prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code org.bitcoin.crawler.PeerSeeds}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.bitcoin.crawler.PeerSeedProtos.PeerSeeds, Builder> implements
        // @@protoc_insertion_point(builder_implements:org.bitcoin.crawler.PeerSeeds)
        org.bitcoin.crawler.PeerSeedProtos.PeerSeedsOrBuilder {
      // Construct using org.bitcoin.crawler.PeerSeedProtos.PeerSeeds.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
       */
      @java.lang.Override
      public java.util.List<org.bitcoin.crawler.PeerSeedProtos.PeerSeedData> getSeedList() {
        return java.util.Collections.unmodifiableList(
            instance.getSeedList());
      }
      /**
       * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
       */
      @java.lang.Override
      public int getSeedCount() {
        return instance.getSeedCount();
      }/**
       * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
       */
      @java.lang.Override
      public org.bitcoin.crawler.PeerSeedProtos.PeerSeedData getSeed(int index) {
        return instance.getSeed(index);
      }
      /**
       * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
       */
      public Builder setSeed(
          int index, org.bitcoin.crawler.PeerSeedProtos.PeerSeedData value) {
        copyOnWrite();
        instance.setSeed(index, value);
        return this;
      }
      /**
       * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
       */
      public Builder setSeed(
          int index, org.bitcoin.crawler.PeerSeedProtos.PeerSeedData.Builder builderForValue) {
        copyOnWrite();
        instance.setSeed(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
       */
      public Builder addSeed(org.bitcoin.crawler.PeerSeedProtos.PeerSeedData value) {
        copyOnWrite();
        instance.addSeed(value);
        return this;
      }
      /**
       * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
       */
      public Builder addSeed(
          int index, org.bitcoin.crawler.PeerSeedProtos.PeerSeedData value) {
        copyOnWrite();
        instance.addSeed(index, value);
        return this;
      }
      /**
       * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
       */
      public Builder addSeed(
          org.bitcoin.crawler.PeerSeedProtos.PeerSeedData.Builder builderForValue) {
        copyOnWrite();
        instance.addSeed(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
       */
      public Builder addSeed(
          int index, org.bitcoin.crawler.PeerSeedProtos.PeerSeedData.Builder builderForValue) {
        copyOnWrite();
        instance.addSeed(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
       */
      public Builder addAllSeed(
          java.lang.Iterable<? extends org.bitcoin.crawler.PeerSeedProtos.PeerSeedData> values) {
        copyOnWrite();
        instance.addAllSeed(values);
        return this;
      }
      /**
       * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
       */
      public Builder clearSeed() {
        copyOnWrite();
        instance.clearSeed();
        return this;
      }
      /**
       * <code>repeated .org.bitcoin.crawler.PeerSeedData seed = 1;</code>
       */
      public Builder removeSeed(int index) {
        copyOnWrite();
        instance.removeSeed(index);
        return this;
      }

      /**
       * <pre>
       * seconds since UNIX epoch
       * </pre>
       *
       * <code>required uint64 timestamp = 2;</code>
       * @return Whether the timestamp field is set.
       */
      @java.lang.Override
      public boolean hasTimestamp() {
        return instance.hasTimestamp();
      }
      /**
       * <pre>
       * seconds since UNIX epoch
       * </pre>
       *
       * <code>required uint64 timestamp = 2;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return instance.getTimestamp();
      }
      /**
       * <pre>
       * seconds since UNIX epoch
       * </pre>
       *
       * <code>required uint64 timestamp = 2;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        copyOnWrite();
        instance.setTimestamp(value);
        return this;
      }
      /**
       * <pre>
       * seconds since UNIX epoch
       * </pre>
       *
       * <code>required uint64 timestamp = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        copyOnWrite();
        instance.clearTimestamp();
        return this;
      }

      /**
       * <code>required string net = 3;</code>
       * @return Whether the net field is set.
       */
      @java.lang.Override
      public boolean hasNet() {
        return instance.hasNet();
      }
      /**
       * <code>required string net = 3;</code>
       * @return The net.
       */
      @java.lang.Override
      public java.lang.String getNet() {
        return instance.getNet();
      }
      /**
       * <code>required string net = 3;</code>
       * @return The bytes for net.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNetBytes() {
        return instance.getNetBytes();
      }
      /**
       * <code>required string net = 3;</code>
       * @param value The net to set.
       * @return This builder for chaining.
       */
      public Builder setNet(
          java.lang.String value) {
        copyOnWrite();
        instance.setNet(value);
        return this;
      }
      /**
       * <code>required string net = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNet() {
        copyOnWrite();
        instance.clearNet();
        return this;
      }
      /**
       * <code>required string net = 3;</code>
       * @param value The bytes for net to set.
       * @return This builder for chaining.
       */
      public Builder setNetBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNetBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.bitcoin.crawler.PeerSeeds)
    }
    private byte memoizedIsInitialized = 2;
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new org.bitcoin.crawler.PeerSeedProtos.PeerSeeds();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "seed_",
              org.bitcoin.crawler.PeerSeedProtos.PeerSeedData.class,
              "timestamp_",
              "net_",
            };
            java.lang.String info =
                "\u0001\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0001\u0003\u0001\u041b\u0002\u1503" +
                "\u0000\u0003\u1508\u0001";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<org.bitcoin.crawler.PeerSeedProtos.PeerSeeds> parser = PARSER;
          if (parser == null) {
            synchronized (org.bitcoin.crawler.PeerSeedProtos.PeerSeeds.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<org.bitcoin.crawler.PeerSeedProtos.PeerSeeds>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:org.bitcoin.crawler.PeerSeeds)
    private static final org.bitcoin.crawler.PeerSeedProtos.PeerSeeds DEFAULT_INSTANCE;
    static {
      PeerSeeds defaultInstance = new PeerSeeds();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        PeerSeeds.class, defaultInstance);
    }

    public static org.bitcoin.crawler.PeerSeedProtos.PeerSeeds getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PeerSeeds> PARSER;

    public static com.google.protobuf.Parser<PeerSeeds> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface SignedPeerSeedsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.bitcoin.crawler.SignedPeerSeeds)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required bytes peer_seeds = 1;</code>
     * @return Whether the peerSeeds field is set.
     */
    boolean hasPeerSeeds();
    /**
     * <code>required bytes peer_seeds = 1;</code>
     * @return The peerSeeds.
     */
    com.google.protobuf.ByteString getPeerSeeds();

    /**
     * <code>required bytes signature = 2;</code>
     * @return Whether the signature field is set.
     */
    boolean hasSignature();
    /**
     * <code>required bytes signature = 2;</code>
     * @return The signature.
     */
    com.google.protobuf.ByteString getSignature();

    /**
     * <code>required bytes pubkey = 3;</code>
     * @return Whether the pubkey field is set.
     */
    boolean hasPubkey();
    /**
     * <code>required bytes pubkey = 3;</code>
     * @return The pubkey.
     */
    com.google.protobuf.ByteString getPubkey();
  }
  /**
   * Protobuf type {@code org.bitcoin.crawler.SignedPeerSeeds}
   */
  public  static final class SignedPeerSeeds extends
      com.google.protobuf.GeneratedMessageLite<
          SignedPeerSeeds, SignedPeerSeeds.Builder> implements
      // @@protoc_insertion_point(message_implements:org.bitcoin.crawler.SignedPeerSeeds)
      SignedPeerSeedsOrBuilder {
    private SignedPeerSeeds() {
      peerSeeds_ = com.google.protobuf.ByteString.EMPTY;
      signature_ = com.google.protobuf.ByteString.EMPTY;
      pubkey_ = com.google.protobuf.ByteString.EMPTY;
    }
    private int bitField0_;
    public static final int PEER_SEEDS_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString peerSeeds_;
    /**
     * <code>required bytes peer_seeds = 1;</code>
     * @return Whether the peerSeeds field is set.
     */
    @java.lang.Override
    public boolean hasPeerSeeds() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required bytes peer_seeds = 1;</code>
     * @return The peerSeeds.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPeerSeeds() {
      return peerSeeds_;
    }
    /**
     * <code>required bytes peer_seeds = 1;</code>
     * @param value The peerSeeds to set.
     */
    private void setPeerSeeds(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
      peerSeeds_ = value;
    }
    /**
     * <code>required bytes peer_seeds = 1;</code>
     */
    private void clearPeerSeeds() {
      bitField0_ = (bitField0_ & ~0x00000001);
      peerSeeds_ = getDefaultInstance().getPeerSeeds();
    }

    public static final int SIGNATURE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString signature_;
    /**
     * <code>required bytes signature = 2;</code>
     * @return Whether the signature field is set.
     */
    @java.lang.Override
    public boolean hasSignature() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required bytes signature = 2;</code>
     * @return The signature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }
    /**
     * <code>required bytes signature = 2;</code>
     * @param value The signature to set.
     */
    private void setSignature(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000002;
      signature_ = value;
    }
    /**
     * <code>required bytes signature = 2;</code>
     */
    private void clearSignature() {
      bitField0_ = (bitField0_ & ~0x00000002);
      signature_ = getDefaultInstance().getSignature();
    }

    public static final int PUBKEY_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString pubkey_;
    /**
     * <code>required bytes pubkey = 3;</code>
     * @return Whether the pubkey field is set.
     */
    @java.lang.Override
    public boolean hasPubkey() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required bytes pubkey = 3;</code>
     * @return The pubkey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPubkey() {
      return pubkey_;
    }
    /**
     * <code>required bytes pubkey = 3;</code>
     * @param value The pubkey to set.
     */
    private void setPubkey(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000004;
      pubkey_ = value;
    }
    /**
     * <code>required bytes pubkey = 3;</code>
     */
    private void clearPubkey() {
      bitField0_ = (bitField0_ & ~0x00000004);
      pubkey_ = getDefaultInstance().getPubkey();
    }

    public static org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code org.bitcoin.crawler.SignedPeerSeeds}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds, Builder> implements
        // @@protoc_insertion_point(builder_implements:org.bitcoin.crawler.SignedPeerSeeds)
        org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeedsOrBuilder {
      // Construct using org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required bytes peer_seeds = 1;</code>
       * @return Whether the peerSeeds field is set.
       */
      @java.lang.Override
      public boolean hasPeerSeeds() {
        return instance.hasPeerSeeds();
      }
      /**
       * <code>required bytes peer_seeds = 1;</code>
       * @return The peerSeeds.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPeerSeeds() {
        return instance.getPeerSeeds();
      }
      /**
       * <code>required bytes peer_seeds = 1;</code>
       * @param value The peerSeeds to set.
       * @return This builder for chaining.
       */
      public Builder setPeerSeeds(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPeerSeeds(value);
        return this;
      }
      /**
       * <code>required bytes peer_seeds = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPeerSeeds() {
        copyOnWrite();
        instance.clearPeerSeeds();
        return this;
      }

      /**
       * <code>required bytes signature = 2;</code>
       * @return Whether the signature field is set.
       */
      @java.lang.Override
      public boolean hasSignature() {
        return instance.hasSignature();
      }
      /**
       * <code>required bytes signature = 2;</code>
       * @return The signature.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getSignature() {
        return instance.getSignature();
      }
      /**
       * <code>required bytes signature = 2;</code>
       * @param value The signature to set.
       * @return This builder for chaining.
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSignature(value);
        return this;
      }
      /**
       * <code>required bytes signature = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignature() {
        copyOnWrite();
        instance.clearSignature();
        return this;
      }

      /**
       * <code>required bytes pubkey = 3;</code>
       * @return Whether the pubkey field is set.
       */
      @java.lang.Override
      public boolean hasPubkey() {
        return instance.hasPubkey();
      }
      /**
       * <code>required bytes pubkey = 3;</code>
       * @return The pubkey.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPubkey() {
        return instance.getPubkey();
      }
      /**
       * <code>required bytes pubkey = 3;</code>
       * @param value The pubkey to set.
       * @return This builder for chaining.
       */
      public Builder setPubkey(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPubkey(value);
        return this;
      }
      /**
       * <code>required bytes pubkey = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPubkey() {
        copyOnWrite();
        instance.clearPubkey();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.bitcoin.crawler.SignedPeerSeeds)
    }
    private byte memoizedIsInitialized = 2;
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "peerSeeds_",
              "signature_",
              "pubkey_",
            };
            java.lang.String info =
                "\u0001\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0003\u0001\u150a\u0000\u0002" +
                "\u150a\u0001\u0003\u150a\u0002";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds> parser = PARSER;
          if (parser == null) {
            synchronized (org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:org.bitcoin.crawler.SignedPeerSeeds)
    private static final org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds DEFAULT_INSTANCE;
    static {
      SignedPeerSeeds defaultInstance = new SignedPeerSeeds();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        SignedPeerSeeds.class, defaultInstance);
    }

    public static org.bitcoin.crawler.PeerSeedProtos.SignedPeerSeeds getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SignedPeerSeeds> PARSER;

    public static com.google.protobuf.Parser<SignedPeerSeeds> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
